version: '3.8'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
      - ./frontend/nginx/ssl/private.key:/etc/nginx/ssl/private.key
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:                      
      - "5000:5000"
    environment:
      NODE_ENV: production
