# version: '3.8'
# services:
#   web:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "443:443"
#     volumes:
#       - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./frontend/nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt
#       - ./frontend/nginx/ssl/private.key:/etc/nginx/ssl/private.key
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:                      
#       - "5000:5000"
#     environment:
#       NODE_ENV: production


version: '3.8'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt  # Папка для Let's Encrypt
      - ./frontend/nginx/ssl:/etc/nginx/ssl  # Папка для SSL
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./frontend/nginx/certbot:/var/www/certbot 
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always